# Generated by Django 5.0.4 on 2025-02-19 18:27

from django.db import migrations


def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")

    # TODO: research the F object and how to do the task in one query
    people = PersonModel.objects.all() # [PersonObject1, PersonObject2, ...]

    for person in people:
        if person.age <= 12:
            person.age_group = "Child"
        elif person.age <= 17:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"

        person.save()  # Bad practice because you are making too much queries to the DB


def set_age_group_default(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")
    default_age_group = PersonModel._meta.get_field("age_group").default

    # TODO: make it update once, hint: use bulk_update
    for person in PersonModel.objects.all():
        person.age_group = default_age_group
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(
            code=set_age_group,
            reverse_code=set_age_group_default,
        )
    ]
