# Generated by Django 5.0.4 on 2025-02-19 18:48
from datetime import timedelta

from django.db import migrations

from main_app.choices import OrderStatusChoices


def update_delivery_and_warranty(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")

    # TODO: do it better with F object
    for order in OrderModel.objects.all():
        if order.status == OrderStatusChoices.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == OrderStatusChoices.COMPLETED:
            order.warranty = "24 months"
            order.save()
        elif order.status == OrderStatusChoices.CANCELLED:
            order.delete()


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_order'),
    ]

    operations = [
        migrations.RunPython(
            code=update_delivery_and_warranty,
            reverse_code=reverse_migration
        )
    ]
