# Generated by Django 5.0.4 on 2025-02-19 19:25

from django.db import migrations


def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")

    for item in ItemModel.objects.all():
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"

        item.save()


def reset_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    default_rarity = ItemModel._meta.get_field("rarity").default

    for item in ItemModel.objects.all():
        item.rarity = default_rarity
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_item'),
    ]

    operations = [
        migrations.RunPython(
            code=set_rarity,
            reverse_code=reset_rarity,
        )
    ]
