# Generated by Django 5.0.4 on 2025-11-06 19:05

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, null=True),
        ),
    ]
